language: rust
rust:
  - 1.23.0
  - 1.24.0
  - 1.25.0
  - stable
  - beta
  - nightly
matrix:
  # allow_failures:
  #   - rust: nightly
  include:
    - env: RUSTFMT
      rust: nightly
      install:
        - rustup component add rustfmt-preview
        - cargo install --force rustfmt-nightly # TODO: this update takes ~8 mins.
      before_script:
        - cargo-fmt fmt -- --version
      script:
        - cargo fmt -- --write-mode=diff
script:
  - cargo test
